### ISSUE TITLE
issue with connecting mongo db

### ISSUE THREAD

**Issue by terriblecoder1** [Sank6/Discord-Bot-List#282]
can anyone help me connect mongodb? I am also having issues with deploying the site it gives me error and i'm not sure what to do

**Comment by Sank6** [comment]
Can you send the error(s)

**Comment by terriblecoder1** [comment]
https://gyazo.com/74e19b811f8d35b82f3adcfbd37ab5c4

I also need help setting up the config and connecting mongo db, your tutorial wasn't too understanding for me and got me confused.

**Comment by terriblecoder1** [comment]
new error: https://gyazo.com/3a39937d0afcfc0b304438d39f6aa4dc

**Comment by terriblecoder1** [comment]
I am also not sure how to connect discord api and stuff

**Comment by terriblecoder1** [comment]
Now its working for me but I want to know how to access my mongodb cluster so I can view my website

**Comment by Sank6** [comment]
The Discord creds are self explanatory. You just need thr information from the developer page on Discord. 
For MongoDB, if you're self hosting, use `mongodb://localhost:PORT/DATABASE_NAME`. If you're using an external one, like Atlas, it gives you the connection string to put in your config file.

**Comment by terriblecoder1** [comment]
> The Discord creds are self explanatory. You just need thr information from the developer page on Discord.
> For MongoDB, if you're self hosting, use `mongodb://localhost:PORT/DATABASE_NAME`. If you're using an external one, like Atlas, it gives you the connection string to put in your config file.
I already connected to the database of mongodb now I can't access my site, the config file is already done.

**Comment by Sank6** [comment]
Try `localhost`

**Comment by terriblecoder1** [comment]
I did just now, the site itself isn't showing up at all. is there a way to deploy this thing? I followed all the steps in the wiki help, I connected to the mongodb database too and when I viewed the site it just shows me my files... something has to be wrong.

**Comment by Sank6** [comment]
If it's showing you your files, then you're not actually running it. To "deploy" it, run `npm start`

**Comment by terriblecoder1** [comment]
I did npm start https://gyazo.com/83564c17c3b7dd303c5eac043a40593a this is what it shows.

**Comment by Sank6** [comment]
Then it's running on port 80.

**Comment by terriblecoder1** [comment]
so what am I supposed to do now?

**Comment by Sank6** [comment]
It should be accesible on `localhost`

**Comment by terriblecoder1** [comment]
I tried still not working

**Comment by Sank6** [comment]
It's something related to your setup but if it says it's running on port 80, it should be working. I guess you can try changing the port but I don't know what else could cause this issue.

**Comment by Zaid-maker** [comment]
The most common port for mongo is 2271 I think

**Comment by Zaid-maker** [comment]
instead of using localhost thing use connection string through mongodb compass

**Comment by Sank6** [comment]
I think his issue is with accessing the site, not the mongodb connection

**Comment by terriblecoder1** [comment]
Yeah it is with accessing the site, the mongodb is connected. I followed all the steps and it still doesn't let me access the site :(

**Comment by terriblecoder1** [comment]
Already found a new project that works, I am just going to close this. thank you guys.
